// <auto-generated />
namespace Web_omlate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sessionCast : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sessionCast));
        
        string IMigrationMetadata.Id
        {
            get { return "201601041713531_sessionCast"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
