// <auto-generated />
namespace Web_omlate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class intinquestionid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intinquestionid));
        
        string IMigrationMetadata.Id
        {
            get { return "201610161306024_int in questionid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
